arm_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - rotation
    - elbow1
    - elbow2
    - wrist
  gains:
    rotation:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    elbow1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    elbow2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    wrist:
      p: 100
      d: 1
      i: 1
      i_clamp: 1